### ISSUE TITLE
исправить две ошибки в HTML

### ISSUE THREAD

**Issue by baigazytb** [baigazy47/html_group_9_homework_34_baigazy_torobek_uulu#2]
Описание
HTML
это http://clip2net.com/s/3JAxfUu не форма, это ссылка на модальное окно с формой, не нужно было здесь использовать теги <form></form> -1
правильнее было бы все сделать одной ссылкой http://clip2net.com/s/3JC4icn , кроме того картинки аватаров нужно было вырезать квадратными и скруглить средствами css -1

Задачи 
1 - убрать теги form и стилизовать ссылку под макету
2 - картинок аватаров срезать квадратными и объединить в одну ссылку 

Время работы 
25 минут

**Comment by baigazy47** [comment]
все ошибки поправил с предыдущими задачами
